- name: Add an apt key by id from a keyserver
  apt_key:
    url: https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key

- name: configure owncloud
  shell: echo 'deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /' | sudo tee /etc/apt/sources.list.d/owncloud.list

- name: install owncloud-files
  apt:
    name: owncloud-files
    update_cache: yes

- name: occ - maintenance:install
  ignore_errors: yes
  shell: sudo -u www-data php occ maintenance:install --database="Mysql" --database-name="owncloud" --database-host="{{ item }}" --database-user="owncloud" --database-pass="{{ password }}" --admin-user="owncloud" --admin-pass="{{ password }}"
  args:
    chdir: /var/www/owncloud
  with_inventory_hostnames:
    - database

# - name: get my public IP
#   ipify_facts:

# - name: set config
#   shell: sed -i "8c 0 => '{{ ipify_public_ip }}'," /var/www/owncloud/config/config.php
#   args:
#     chdir: /var/www/owncloud


# - name: copying template file
#   copy:
#     src: templates/owncloud
#     dest: /var/www/owncloud/config/config.php

# - name: replace keywords password
#   replace:
#     dest: /var/www/owncloud/config/config.php
#     regexp: '@database_ip'
#     replace: "{{ item }}"
#     with_inventory_hostnames:
#       - database


# - name: create database for owncloud
#   mysql_db：
#     name: "{{ dbname }}"
#     login_host: "{{ hostname }}"
#     login_password: "{{ password }}"
#     login_user: "{{ username }}"
#     login_port: "{{ port }}"
#     state: present


