# This playbook creates a new GCP instance
# using the variables defined in vars.yml
# as the configuration of the instance.

# this playbook also setups up SSH access.

# get the public key to use on the new instance
- name: get public-key
  shell: cat ~/.ssh/id_rsa.pub
  register: publickey

- name: who
  shell: whoami
  register: name

# create a GCP instance using details in vars.yml
- name: Launch instances
  gce:
    instance_names: "{{ instance_name }}"
    machine_type: "{{ instance.machine_type }}"
    image: "{{ instance.image }}"
    service_account_email: ""
    credentials_file: ""
    project_id: "{{ project_id }}"
    zone: "{{ instance.zone }}"
    metadata: "{ 'ssh-keys': '{{ name.stdout_lines.0 }}:{{ publickey.stdout_lines.0 }}' }"
    tags: "{{ instance_tags }}"
  register: gce


- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
  with_items: "{{ gce.instance_data }}"

- name: Add host to groupname
  add_host: hostname={{ item.public_ip }} groupname="{{ instance_group }}"
  with_items: "{{ gce.instance_data }}"
