# just a test

---
- name: create NFS clients (webservers)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ws_instances:
      - ws01
      - ws02
    instance_group: ws

  vars_files:
    - vars/all.yml

  tasks:
    - name: Create webserver(s)
      include_tasks: tasks/gce_create_instance.yml
      vars:
        instance_name: "{{ item }}"
      with_items:
        - "{{ ws_instances }}"

- hosts: ws
  become: true
  become_user: root
  gather_facts: yes

  roles:
    - nfs-client
