- name: add xfs support using xfsprogs package
  apt: name=xfsprogs

- name: check if the ssd is already mounted
  shell: mount | grep /dev/sdb
  ignore_errors: yes
  register: mounted

- name: format the ssd as xfs
  filesystem:
    fstype: xfs
    dev: /dev/sdb
    force: yes
  when: mounted is failed

- name: create network directory
  file:
    name: /share/
    state: directory

- name: mount the ssd
  mount:
    name: /share/
    src: /dev/sdb
    fstype: xfs
    state: mounted